In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('C:/Users/User/dads4002/2021-2022.csv')

In [3]:
pl = df
pl.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/8/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/8/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/8/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/8/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/8/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86

**1.English Premier League มีกี่ทีม ทีมอะไรบ้าง**

In [4]:
pl_teams = pl["HomeTeam"].unique()
len(pl_teams)
print(f'English Premier League have {len(pl_teams)} teams. \n {pl_teams}')

English Premier League have 20 teams.
 ['Brentford' 'Man United' 'Burnley' 'Chelsea' 'Everton' 'Leicester'
 'Watford' 'Norwich' 'Newcastle' 'Tottenham' 'Liverpool' 'Aston Villa'
 'Crystal Palace' 'Leeds' 'Man City' 'Brighton' 'Southampton' 'Wolves'
 'Arsenal' 'West Ham']

**2.การแข่งขันเกิดขึ้นที่สนาม Oldtrafford**

In [5]:
oldtrafford = pl[pl["HomeTeam"] == "Man United"]
oldtrafford

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
1,E0,14/8/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
34,E0,11/9/2021,15:00,Man United,Newcastle,4,1,H,1,0,...,2.80,-2.00,1.99,1.94,1.99,1.92,2.01,2.07,1.92,1.95
51,E0,25/9/2021,12:30,Man United,Aston Villa,0,1,A,0,0,...,2.33,-1.25,1.95,1.98,1.95,1.97,1.98,2.07,1.91,1.98
60,E0,2/10/2021,12:30,Man United,Everton,1,1,D,1,0,...,2.05,-1.00,1.97,1.96,1.97,1.95,1.98,2.10,1.92,1.96
89,E0,24/10/2021,16:30,Man United,Liverpool,0,5,A,0,4,...,2.60,0.25,1.88,2.05,1.89,2.04,1.92,2.08,1.85,2.04
101,E0,6/11/2021,12:30,Man United,Man City,0,2,A,0,2,...,2.27,0.75,2.00,1.93,2.00,1.93,2.03,2.06,1.97,1.92
138,E0,2/12/2021,20:15,Man United,Arsenal,3,2,H,1,1,...,2.15,-0.25,1.77,2.14,1.81,2.11,1.85,2.20,1.80,2.11
145,E0,5/12/2021,14:00,Man United,Crystal Palace,1,0,H,0,0,...,2.23,-1.00,1.88,2.02,1.91,2.01,1.93,2.15,1.86,2.02
182,E0,30/12/2021,20:15,Man United,Burnley,3,1,H,3,1,...,2.17,-1.25,1.88,2.05,1.88,2.04,1.90,2.07,1.85,2.04
190,E0,3/1/2022,17:30,Man United,Wolves,0,1,A,0,0,...,1.75,-0.75,2.00,1.95,1.97,1.95,2.00,2.15,1.90,1.99
208,E0,22/1/2022,15:00,Man United,West Ham,1,0,H,0,0,...,2.16,-0.25,1.85,2.08,1.88,2.05,1.89,2.24,1.82,2.08
224,E0,12/2/2022,12:30,Man United,Southampton,1,1,D,1,0,...,2.45,-1.00,1.89,2.04,1.88,2.04,2.05,2.14,1.91,1.97
233,E0,15/2/2022,20:15,Man United,Brighton,2,0,H,0,0,...,1.86,-0.50,1.75,2.05,1.81,2.10,1.93,2.19,1.84,2.04
252,E0,26/2/2022,15:00,Man United,Watford,0,0,D,0,0,...,2.15,-1.25,1.87,2.03,1.88,2.05,1.91,2.19,1.86,2.03
273,E0,12/3/2022,17:30,Man United,Tottenham,3,2,H,2,1,...,2.04,-0.25,2.03,1.90,2.06,1.87,2.15,1.91,2.02,1.86
294,E0,2/4/2022,17:30,Man United,Leicester,1,1,D,0,0,...,2.34,-1.00,1.90,2.00,1.93,2.00,2.10,2.00,1.95,1.92
310,E0,16/4/2022,15:00,Man United,Norwich,3,2,H,2,1,...,2.97,-1.75,1.92,1.98,1.99,1.97,1.99,2.01,1.94,1.93
331,E0,28/4/2022,19:45,Man United,Chelsea,1,1,D,0,0,...,2.04,0.50,1.77,2.02,1.81,2.12,1.85,2.14,1.80,2.09
341,E0,2/5/2022,20:00,Man United,Brentford,3,0,H,1,0,...,2.20,-0.75,2.01,1.89,2.04,1.89,2.04,2.04,1.98,1.90

**3.นัดที่แมนยูแพ้ใครเป็นผู้ตัดสินบ้าง** (ปฏิเสธไม่ได้ว่าในการแข่งขันฟุตบอลนั้น ผู้ตัดสินนั้นเป็นตัวแปรสำคัญในการแข่งขัน จึงต้องการทราบชื่อผู้ตัดสินในเกสม์ที่แพ้ เพื่อวิเคราะห์ว่าอาจจะมีผู้ตัดสินคนไหนที่ให้การตัดสินไม่เป็นธรรม)

ผลการแข่งขันแต่ละนัดของ Man United

In [6]:
manu_matches = pl[(pl["HomeTeam"] == "Man United") | (pl["AwayTeam"] == "Man United")]
man_u = manu_matches.loc[:, ["HomeTeam","AwayTeam","FTHG","FTAG","FTR"]]
man_u

           HomeTeam        AwayTeam  FTHG  FTAG FTR
1        Man United           Leeds     5     1   H
16      Southampton      Man United     1     1   D
29           Wolves      Man United     0     1   A
34       Man United       Newcastle     4     1   H
48         West Ham      Man United     1     2   A
51       Man United     Aston Villa     0     1   A
60       Man United         Everton     1     1   D
72        Leicester      Man United     4     2   H
89       Man United       Liverpool     0     5   A
96        Tottenham      Man United     0     3   A
101      Man United        Man City     0     2   A
115         Watford      Man United     4     1   H
128         Chelsea      Man United     1     1   D
138      Man United         Arsenal     3     2   H
145      Man United  Crystal Palace     1     0   H
154         Norwich      Man United     0     1   A
175       Newcastle      Man United     1     1   D
182      Man United         Burnley     3     1   H
190      Man United          Wolves     0     1   A
198     Aston Villa      Man United     2     2   D
203       Brentford      Man United     1     3   A
208      Man United        West Ham     1     0   H
217         Burnley      Man United     1     1   D
224      Man United     Southampton     1     1   D
233      Man United        Brighton     2     0   H
242           Leeds      Man United     2     4   A
252      Man United         Watford     0     0   D
265        Man City      Man United     4     1   H
273      Man United       Tottenham     3     2   H
294      Man United       Leicester     1     1   D
300         Everton      Man United     1     0   H
310      Man United         Norwich     3     2   H
315       Liverpool      Man United     4     0   H
321         Arsenal      Man United     3     1   H
331      Man United         Chelsea     1     1   D
341      Man United       Brentford     3     0   H
346        Brighton      Man United     4     0   H
375  Crystal Palace      Man United     1     0   H

ผู้ตัดสินในแต่ละนัดที่แมนยูแพ้

In [7]:
referee = manu_matches.loc[:, ["HomeTeam","AwayTeam","FTHG","FTAG","FTR","Referee"]]
ref_away = referee[(referee["AwayTeam"] == "Man United") & (referee["FTR"] == "H")]
ref_home = referee[(referee["HomeTeam"] == "Man United") & (referee["FTR"] == "A")]
manu_loss = pd.concat([ref_away, ref_home])
sort_manu_loss= manu_loss.sort_values(by=['FTHG', 'FTAG'], ascending=[False, False])
sort_manu_loss

           HomeTeam     AwayTeam  FTHG  FTAG FTR     Referee
72        Leicester   Man United     4     2   H    C Pawson
115         Watford   Man United     4     1   H      J Moss
265        Man City   Man United     4     1   H    M Oliver
315       Liverpool   Man United     4     0   H  M Atkinson
346        Brighton   Man United     4     0   H    A Madley
321         Arsenal   Man United     3     1   H    C Pawson
300         Everton   Man United     1     0   H      J Moss
375  Crystal Palace   Man United     1     0   H  M Atkinson
89       Man United    Liverpool     0     5   A    A Taylor
101      Man United     Man City     0     2   A    M Oliver
51       Man United  Aston Villa     0     1   A      M Dean
190      Man United       Wolves     0     1   A      M Dean

**4.ทีมเยือนที่ชนะด้วยสกอร์ห่างที่สุด 3 อันดับ**

In [8]:
away_team = pl.loc[pl["FTR"] == "A", ['HomeTeam', 'AwayTeam', 'FTHG', 'FTAG']]
away_team['FTAG-FTHG'] = away_team['FTAG'] - away_team['FTHG']
max = away_team.nlargest(5, 'FTAG-FTHG')
max

        HomeTeam   AwayTeam  FTHG  FTAG  FTAG-FTHG
302  Southampton    Chelsea     0     6          6
70       Watford  Liverpool     0     5          5
89    Man United  Liverpool     0     5          5
170      Norwich    Arsenal     0     5          5
379      Norwich  Tottenham     0     5          5

**5.เปอร์เซนต์การแข่งขันชนะ ของเจ้าบ้าน และ ทีมเยือน**

In [9]:
total_matches = len(pl)

home_team = pl.loc[pl["FTR"] == "H"]
home_win = len(home_team)
per_home_win = np.around((home_win / total_matches) * 100, 2)

away_team = pl.loc[pl["FTR"] == "A"]
away_win = len(away_team)
per_away_win = np.around((away_win / total_matches) * 100, 2)

print(f'HomeTeam wins {(per_home_win)}% \nAwayTeam wins {per_away_win}% ')

HomeTeam wins 42.89%
AwayTeam wins 33.95%